### ISSUE TITLE
blurred outilne

### ISSUE THREAD

**Issue by zDemoniac** [cakeslice/Outline-Effect#10]
How we can add blur effect to outline?
I tried adding to OnRenderImage()

blur.OnRenderImage(renderTexture, extraRenderTexture);
outlineShaderMaterial.SetTexture("_OutlineSource", extraRenderTexture);

(where blur is added in Start() like 
BlurOptimized blur = cameraGameObject.AddComponent<BlurOptimized>();)

but looks like shader can't work with blurred texture

**Comment by cakeslice** [comment]
Yeah that won't work, you would have to render the outline (not the outlineSource) to another RenderTexture, blur it, and then merge with the final image
