### ISSUE TITLE
Does not work correctly with multiple cameras (VR)

### ISSUE THREAD

**Issue by AIEUtrecht** [cakeslice/Outline-Effect#13]
When using a Virtual Reality headset (Vive) the outlines are shown slightly to the left of the object on the left screen and slightly to the right of the object on the right scene. This leads to two half transparent outlines on both sides of the object.

**Comment by cakeslice** [comment]
Ok, thanks for reporting, never tested in VR, will look into it when I get a VR headset on my hands.

**Comment by VadimTikhonyuk** [comment]
Hi, I fix this for Google VR

![1](https://cloud.githubusercontent.com/assets/13260375/23254418/b6af1802-f9c0-11e6-8d8f-3680dd5d5f1d.png)
![2](https://cloud.githubusercontent.com/assets/13260375/23254422/b8e7bf66-f9c0-11e6-8b56-699a0e8bf987.png)

**Comment by cakeslice** [comment]
@VadimTikhonyuk 

Just to be clear, does this fix this issue specifically?
"The outlines are shown slightly to the left of the object on the left screen and slightly to the right of the object on the right scene. This leads to two half transparent outlines on both sides of the object."

Or does it only fix the fact that the outline can't render in multiple cameras?

Thanks!

**Comment by VadimTikhonyuk** [comment]
@cakeslice 
This works on Google VR, but I think on HTC Vive will work too, just same logic.

**Comment by cakeslice** [comment]
@VadimTikhonyuk 

Ok, just committed your fix, but until someone tests with a Vive I'll keep this open.

**Comment by ikriz** [comment]
This doesn't work for a Native unity camera with VR enabled, not a solution for VR on the Vive atleast.

**Comment by cakeslice** [comment]
If someone has
