### ISSUE TITLE
Upsidedown outline

### ISSUE THREAD

**Issue by mjholtzem** [cakeslice/Outline-Effect#2]
Just downloaded this and tried it out but the outline is flipped vertically and offset a bunch as if it were an outline of a reflection.
![outlineglitch](https://cloud.githubusercontent.com/assets/1538547/8467208/7ec30498-2029-11e5-886d-effe726f9864.png)

**Comment by Frou-HOS** [comment]
Set in your Quality render settings - Anti Aliasing option to disabled, and the outline come back to the right way

**Comment by mjholtzem** [comment]
Ok thanks I'll give that a try
