### ISSUE TITLE
outline not working with surface shaders

### ISSUE THREAD

**Issue by JesseLeeuwen** [cakeslice/Outline-Effect#21]
I want to add outline to some object in my scene to separate them from the background. The outline wont show with my materials but works fine with the default unity materials see image:

![outline bug](https://cloud.githubusercontent.com/assets/7127763/24829599/27a8263a-1c75-11e7-9777-31f4f95a81cd.PNG)

shader file:
[SHD_ToonShader.zip](https://github.com/cakeslice/Outline-Effect/files/907495/SHD_ToonShader.zip)

EDIT:

i found out that it doesn't show an outline when a object has a texture. I changed line 190 in OutlineEffect.cs to: 
`outline.Renderer.sharedMaterials[m].mainTexture = null; `

**Comment by cakeslice** [comment]
Hummm I tried replicating it with your shader but I can't. Can you send me a project that replicates the issue?
