### ISSUE TITLE
cannot change outline thickness 

### ISSUE THREAD

**Issue by mandelc** [cakeslice/Outline-Effect#23]
Outline-effect is so fantastic. Thanks a lot. But, I cannot change the line thickness even if the demo. Please help.

**Comment by cakeslice** [comment]
I'm sorry but I don't have this issue, what Unity version are you using and what is your target platform? (Windows, Mac, Android...)

**Comment by mandelc** [comment]
Thanks Cakeslice. I am using Unity 5.6 with Windows 10. Any suggestion?

**Comment by cakeslice** [comment]
Sorry but I didn't test the effect on 5.6 yet since it's still early to upgrade in my opinion, can you try 5.5?

**Comment by mandelc** [comment]
Oh, I see. Thanks for your suggestion.
