### ISSUE TITLE
Separate Outlines

### ISSUE THREAD

**Issue by thelucre** [cakeslice/Outline-Effect#28]
Is there a feature to outline individual meshes, not aggregate the entire shape? 

For instance, this image has 7 meshes but the outline is drawn according to the entire silhouette. Can they each have their own outline drawn?

![](http://yo.bkwld.com/0P3h0l2F1W3c/Image%202017-07-09%20at%201.35.53%20PM.png)

**Comment by cakeslice** [comment]
Sorry but this is just the way the effect is supposed to work (it's an image effect after all).

You could have separate outline buffers for each mesh and render each one,  but performance then would be horrible. 

To do this, I suggest you try another asset or approach.
