### ISSUE TITLE
Material doesn't have a texture property '_MainTex'

### ISSUE THREAD

**Issue by SilvanVR** [cakeslice/Outline-Effect#32]
Hey,
i'm using the outline effect for an ARKit Project on an IPad 2017.
It's nice, but i get always this error, when running it on the IPad:
`Material doesn't have a texture property '_MainTex'
cakeslice.OutlineEffect:OnPreRender()

[/Users/builduser/buildslave/unity/build/Runtime/Shaders/Material.cpp line 1170] 
(Filename: /Users/builduser/buildslave/unity/build/Runtime/Shaders/Material.cpp Line: 1170)`

Do you know how to fix it? (Googled it, but didnt help me. Sorry!)
Thanks :)

**Comment by cakeslice** [comment]
Fixed in #41
