### ISSUE TITLE
Rendering LODs

### ISSUE THREAD

**Issue by miroki123** [cakeslice/Outline-Effect#56]
There's a problem when rendering LODs using this Outline-Effect plugin. If you have a LOD swap in the middle of an animation, the outline will encompass both LOD renderers.

I tried creating a pull request but it's denied, so the way I fixed it on my end was by adding this code to Outline.cs

```
private bool visible;

private void OnBecameVisible()
{
    visible = true;
}

private void OnBecameInvisible()
{
    visible = false;
}

public bool IsVisible => visible;
```

And then this code to OutlineEffect.cs

```
foreach (Outline outline in outlines)
{
    if (!outline.IsVisible)
        continue;
```

**Comment by cakeslice** [comment]
"I tried creating a pull request but it's denied" - Weird, what is the message?

Thanks for your contribution, I will push this.

You put the check here right?
![image](https://user-images.githubusercontent.com/7516142/114430470-5eb1dd00-9bb6-11eb-8ecc-62851c0da845.png)

**Comment by miroki123** [comment]
Exactly. Thanks for this amazing plugin!
