### ISSUE TITLE
Option to change line thicknes, intensity, fill ammount and so per color/object

### ISSUE THREAD

**Issue by astromediaonly** [cakeslice/Outline-Effect#58]
Would be possible to do this? Its not that important but it would be nice to have different settings accessable "localy" (from `Outline` script possibly?) so it could be changed based on other factors (importance of outlined object in scene, to more distinguish between different outline purposes and so).

**Comment by cakeslice** [comment]
It's not possible because it's a screen space effect, it's applied to the entire scene in the same way (except for colors)
